### ISSUE TITLE
Task-based login

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#15]
### User story
As a site user, in order to access appropriate section of the portal, I would like to be able to select a task I want to accomplish during the login process.

**Acceptance Criteria:**

- [ ] A user can select a task they want to accomplish in order to login to the portal (wording of the below labels might change):
  - [ ] Create and manage a challenge
  - [ ] Manage submissions and build evaluations
  - [ ] Evaluate submissions
  - [ ] Solve challenges
- [ ] A user is logged in to appropriate section of the portal based on their selected task and assigned role
  - [ ] Create and manage a challenge => challenge manager => Phoenix app (#13 )
  - [ ] Create and manage an evaluation => challenge manager => Rails app (#13 )
  - [ ] Review and evaluate submissions => evaluator => Rails app (#16 )
  - [ ] Submit a solution to a challenge => public solver => Phoenix app (#23 )
- [ ] A user is logged in to all site sections (based on their role) with a single login

### Definition of Done

**Doing (dev team)**
- [ ] Code complete 
- [ ] Code is organized appropriately
- [ ] Any known trade offs are documented in the associated GH issue
- [ ] Code is documented, modules, shared functions, etc.
- [ ] Automated testing has been added or updated in response to changes in this PR
- [ ] The feature is smoke tested to confirm it meets requirements
- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks
- [ ] PR that changes or adds UI
  - [ ] include a screenshot of the WAVE report for the altered pages
  - [ ] Confirm changes were validated for mobile responsiveness
- [ ] PR approved / Peer reviewed 
- [ ] Security scans passed
- [ ] Automate accessibility tests passed
- [ ] Build process and deployment is automated and repeatable
- [ ] Feature toggles if appropriate
- [ ] Deploy to staging
- [ ] Move card to testing column in the board
---
**Staging**
- [ ] Accessibility tested (Marni)
  - [ ]  Keyboard navigation
  - [ ]  Focus confirmed
  - [ ] Color contrast compliance
  - [ ] Screen reader testing 
- [ ] Usability testing: mobile and desktop (Tracy or Marni)
- [ ] Cross browser testing (tool to be determined) (Tracy or Marni)
  - [ ]  UI rendering is performant
- [ ] AC review (Renata)
- [ ] Deploy to production (production-like environment for eval capability) (dev team)
- [ ] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
A question for login.gov:

- can they filter state and local accounts

**Comment by r-bartlett-gsa** [comment]
@stepchud Here's a task-based login diagram to help visualize this user workflow:  [Task-based login diagram_1.pdf](https://github.com/user-attachments/files/16274914/Task-based.login.diagram_1.pdf)

You can also view it in [Mural](https://app.mural.co/t/gsa6/m/gsa6/1714654821089/85c0a42b8b23703837b34773e3ffd8e0965c8f8c?sender=renatabartlett1206)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/bd1dcc3f-a032-4865-951c-72d2ea16858a)


Figma link: https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=29-3530&t=STCLmrRsXj3cnZKx-0

**Comment by r-bartlett-gsa** [comment]
@stepchud If there aren't any concerns with this story, should we move it back to the sprint backlog?

**Comment by afeijoo** [comment]
Archiving repo; no longer applicable.
