### ISSUE TITLE
Submissions on the Rails App - Challenge Managers

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#33]
### User story
As a challenge manager or evaluator, in order to manager evaluations process efficiently, I would like to be able to access submissions on the same app as Evaluation Forms.

**Acceptance Criteria:**

- [x] A user can navigate to a page on the Rails app that lists challenges via the dashboard or utility nav:
  - [x] A challenge manager sees a list of challenges they own, and the list displays:
    - [x] Challenge Name, Phase & Status
    - [x] Number of Submissions
    - [x] Evaluation form name and link
    - [x] Evaluations due date
  - [x] ~An evaluator sees a list of challenges they have assigned submission to, and the list displays:~  **moved to #285** 
    - [ ] Challenge Name and Phase
    - [ ] Number of assigned submissions
    - [ ] Number of remaining submissions to evaluate (in progress and not started)
    - [ ] Evaluations due date
    - [ ] If the user does not have any submissions assigned to them, a message is displayed indicating so
- [x] The user can view a list of submission for each challenge:
    - [x]  #59 
    - [x] #82 
- [ ] ~Challenge manager can enter and manage evaluators for the challenge, #74~
- [ ] ~When the user clicks on View Submissions on Phoenix app, they are routed to the Submissions list on the Rails app, #171~

**Development tasks:**

- [x] #196
- [x] #197

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [ ] ~Feature toggles if appropriate~
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [ ] Accessibility tested (Marni)
  - [ ]  Keyboard navigation
  - [ ]  Focus confirmed
  - [x] Color contrast compliance
  - [ ] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [ ] AC review (Renata)
- [ ] Deploy to production (production-like environment for eval capability) (dev team)
- [ ] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
**Some button styles, colors and labels may have changed and screenshots below may reflect outdated styles. Please refer to [Figma](https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=2750-62256&node-type=section&t=6lzkQqYVjlLF4EbT-0) for latest designs.**
Misalignment in styles, colors and labels should not affect the completion of development work. There will be additional user stories towards the end of this epic or MVP to bring uniformity to styles and colors.
If significant difference is noticed in features / functionality, please contact Renata.

### Challenge Managers, mobile
![Image](https://github.com/user-attachments/assets/6ee83474-372e-4455-b499-a3d51c85e4fc)

### Challenge Managers, desktop
![Image](https://github.com/user-attachments/assets/f6047113-64ef-4a8c-ad23-b8209fad9b40)


---
### Evaluators
![Image](https://github.com/user-attachments/assets/71781521-cf7f-4d6f-a600-9a3952a9523f)
![Image](https://github.com/user-attachments/assets/7d563a37-2629-4b94-bccc-02d6f23b4414)

### Evaluators, desktop
![Image](https://github.com/user-attachments/assets/2819792a-f265-4bb4-974c-4894edf3e328)

**Comment by stepchud** [comment]
> When the user clicks on View Submissions on Phoenix app, they are routed to the Submissions list on the Rails app.

we're removing all access to submissions in Phoenix then?

> Challenge manager can enter and manage evaluators for the challenge, https://github.com/GSA/Challenge_platform/issues/74

I would remove this AC from this Story as it's unrelated to submissions

**Comment by r-bartlett-gsa** [comment]
@stepchud 

> we're removing all access to submissions in Phoenix then?


Yes

**Comment by mhotch24** [comment]
@r-bartlett-gsa From https://challenge-dev.app.cloud.gov/ when I log in as a CM, I can only see pages for Submissions & Evaluations, and Evaluation Forms, Resources. When I click on any of the other cards, it asks me to Accept & Log In. When I do, it logs me out of the original areas I had access to and tells me I do not have access.![Image](https://github.com/user-attachments/assets/53aebd6f-9cbc-4459-b323-90af0b6e259d)

**Comment by mhotch24** [comment]
@stepchud A11y testing feedback:

- Data table fails WCAG guidelines, see [1.3.1 info and relationships](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#content-structure-separation-programmatic)
- Needs appropriate labeling of headings etc. to be read by screen readers
  - Table headings aren’t being read in completion
  - One cell is labelled “form-title”
- Additional info for table formatting: https://www.w3.org/WAI/tutorials/tables/one-header/
![Image](https://github.com/user-attachments/assets/ab247659-0e0e-4e80-a51f-7d626b441eaf)

**Comment by r-bartlett-gsa** [comment]
@mhotch24 Please provide a video recording for the A11y issues you are experiencing for this ticket.

**Comment by mhotch24** [comment]
@r-bartlett-gsa A recording is not necessary for this one. This card was from Dec. 2nd A11y testing. Much programming has been done since. In fact, I worked with @stepchud last week to solve for some other table issues and perhaps those helped to resolve these. @stepchud can you confirm?

Here is the only issue still remaining and Stephen can share with Stone how he resolved it.

![Image](https://github.com/user-attachments/assets/2929ac5c-a851-437e-b308-8e3570b0dcbc)
