### ISSUE TITLE
Evaluator's Dashboard

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#52]
### User Story
As a user with an evaluator role, in order to know the full scope of site features available for my role, I would like a dashboard-like page that lists role-specific features.

**Acceptance Criteria:**

- [x] User with assigned evaluator role can navigate to the following Challenge.gov features via a dashboard page:
  - [x] **Submissions** 
    - [x] Takes the user to the Rails app where the user can view submissions assigned to them and evaluate those submissions, #82 
  - [x] **Resources** 
    - [ ] Takes the user to the Rails app where the user can access informational resources, #94 

**Development tasks:**

- [x] #127
- [x] Implement the Evaluator Dashboard based on #127, #126 

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/65068f44-3f6d-4f1c-9f4b-aaa6b455d5cc)

**Comment by r-bartlett-gsa** [comment]
@cpreisinger / @stonefilipczak Since this is in testing column, please review DoD list and check (or cross out) appropriate checkboxes

**Comment by mhotch24** [comment]
Started Usability/A11y/Cross Browser Testing although DOD check boxes are not checked off. 
Still having to use an incognito window for Chrome to avoid the following issue:
This page isn’t workingchallenge-dev.app.cloud.gov redirected you too many times.
[Try deleting your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS

@stonefilipczak 
**Screenreader Testing** 
Redundant Text being read:  Links in utility nav and body CTAs are repeating. Example; "Evaluation forms. Evaluations forms." 
Solution: The icon alt tags are using the same word and the heading. Make all icons decorative using an empty "".

**Comment by mhotch24** [comment]
All testing complete. Two issues found. 

1. icon alt = should be decorative
2. wordmark cut off on mobile (see screen) doesn't necessarily apply to this card but wanted to make aware.![Image](https://github.com/user-attachments/assets/a37352cc-d584-48db-b6d9-1e1d9653f5af)

**Comment by mhotch24** [comment]
@stepchud I'm still getting the same issue. I log in as a CM to https://challenge-dev.app.cloud.gov/dashboard.

**Comment by mhotch24** [comment]
@stepchud  I'm still seeing the logo cut off on mobile. https://challenge-dev.app.cloud.gov/dashboard on mobile

**Comment by mhotch24** [comment]
@r-bartlett-gsa retested and wordmark looks great! Redundant voice over due to repetitive alt label on icons is fixed as well.
Testing is complete.
