### ISSUE TITLE
Challenge Manager's Dashboard (Rails)

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#53]
### User Story
As a user with a challenge manager role, in order to know the full scope of site features available for my role, I would like a dashboard-like page that lists role-specific features.

**Acceptance Criteria:**

- [x] User with assigned challenge manager role can navigate to the following Challenge.gov features via a dashboard page on the Rails app:
  - [x] **Challenges** 
    - [x] Takes the user to the Phoenix app (without needing to re-login) where the user can manage challenges (existing feature)
  - [x] **Evaluation Forms** 
    - [x] Takes the user to the Rails app where the user can create and manager evaluation forms, #60 
  - [x] **Submissions** 
    - [x] Takes the user to the Rails app where the user can manage submissions and evaluation process, #59 
  - [x]  **Message center**
    - [x]  Takes the user to the Phoenix app, where the user can access the existing Message Center section
  - [x]  **Analytics**
    - [x]  Takes the user to the Phoenix app, where the user can access the existing Analytics section
  - [x] **Resources** 
     - [x] Takes the user to [the user guides content on challenge.gov website](https://www.challenge.gov/cm-user-guide/)

**Development tasks:**

- [x] #125
- [x] #126
- [x] Implement the Challenge Manager dashboard menu using links from #125 and components from #126 

### Definition of Done

**Doing (dev team)**
- [ ] Code complete 
- [ ] Code is organized appropriately
- [ ] Any known trade offs are documented in the associated GH issue
- [ ] Code is documented, modules, shared functions, etc.
- [ ] Automated testing has been added or updated in response to changes in this PR
- [ ] The feature is smoke tested to confirm it meets requirements
- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks
- [ ] PR that changes or adds UI
  - [ ] include a screenshot of the WAVE report for the altered pages
  - [ ] Confirm changes were validated for mobile responsiveness
- [ ] PR approved / Peer reviewed 
- [ ] Security scans passed
- [ ] Automate accessibility tests passed
- [ ] Build process and deployment is automated and repeatable
- [ ] Feature toggles if appropriate
- [ ] Deploy to staging
- [ ] Move card to testing column in the board
---
**Staging**
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/dd9fb468-ac11-4617-999f-d96557019e87)

**Comment by r-bartlett-gsa** [comment]
@cpreisinger / @stonefilipczak Since this one is in testing column, please review DoD and check appropriate checkboxes.

**Comment by TCKapGrp** [comment]
@mhotch24 , I was experiencing issues in Mac/Safari with keyboard testing -- specifically tabbing.  Can you check this one please?

Screenreader testing looked clean:
https://challenge-dev.app.cloud.gov/dashboard unselected
Loading page
collapsed
Loading complete
RailsNew
clickable  banner landmark    Primary navigation  navigation landmark    list  with 4 items  link    ind a Challenge
link    Resources
link    Events
link    Contact  out of list
Search component  region    search landmark    Search
edit  
button    graphic    Search  out of region
button    Logout
button    Switch Task
visited  link    graphic    dashboard
clickable  banner landmark    Primary navigation  navigation landmark  list  with 4 items  Resources  link  
Events  link  
Contact  link  
Search component  region
search landmark
Search  edit  blank
Search  graphic    button  
Logout  button  
Switch Task  button  
dashboard  graphic    Dashboard  visited  link  
challenges  graphic    Challenges  visited  link  
Manage Submissions  graphic    Submissions  link  
Evaluation Forms  graphic    Evaluation Forms  link  
Resources  graphic    Resources  link  
main landmark    challenges  graphic    Challenges  heading    level 2  Create and manage challenges.  visited  link  
submissions  graphic    Submissions  heading    level 2  Manage submissions, evaluations, and evaluators.  link  
evaluation forms  graphic    Evaluation Forms  heading    level 2  Create and manage evaluation forms.  link  
help  graphic    Message Center  heading    level 2  View and send messages to Challenge.gov users.  link  
help  graphic    Analytics  heading    level 2  View web analytics data related to your challenges.  link  
resources  graphic    Resources  heading    level 2  Learn how to make the most of the platform.  link  
Challenge Manager Evaluation Dashboard

**Comment by TCKapGrp** [comment]
Per @mhotch24 on a11y, this is not an issue, a setting in Safari browser must be updated so it functions correctly. By default tab-access is disabled in safari. To enable it, check "Preferences > Advanced > Press tab to highlight each item on a page.
