### ISSUE TITLE
Submissions List View for Challenge Managers

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#59]
### User story
As a challenge manager, in order to manage submissions and their evaluations process efficiently, I would like to be able to access all submissions for a single challenge.

**Acceptance Criteria:**

- [x] A challenge manager can view a list of submission for each challenge they manage
  - [x] The submission list view indicates the challenge
  - [x] An evaluation progress summary is displayed, #79 
  - [ ] A challenge manager can export submission data, #58 
  - [x] The list of submissions displays the following information for each submission:
    - [x] Submission ID
    - [x] Eligibility for evaluation status
    - [x] Advancement status
    - [x] Assigned evaluators and their evaluation status (not started, in progress, completed, recused)
    - [x] Average score (only available when all assigned evaluators completed their evaluations)
    - [x] An option to view submission, #80 
  - [x] A challenge manager can sort the list, #57 
    - [x] Default sort is: no assigned evaluators, not started, in progress, completed, not eligible for evaluations
  - [x] Alerts are displayed to inform challenge managers whether they need to reassign evaluators or update their evaluation forms:
    - [x] If a challenge does not have assigned evaluation form
    - [x] If a submission has a recused evaluator
- [x] The page displays 20 submissions on initial load, and the user can load more submission in 20 submission increments

**Development tasks:**

- [x] #205
- [x] #206
- [x] #208
- [x] #209
- [x] #291
- [x] #292
- [x] #293

### Definition of Done

**Doing (dev team)**
- [ ] Code complete 
- [ ] Code is organized appropriately
- [ ] Any known trade offs are documented in the associated GH issue
- [ ] Code is documented, modules, shared functions, etc.
- [ ] Automated testing has been added or updated in response to changes in this PR
- [ ] The feature is smoke tested to confirm it meets requirements
- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks
- [ ] PR that changes or adds UI
  - [ ] include a screenshot of the WAVE report for the altered pages
  - [ ] Confirm changes were validated for mobile responsiveness
- [ ] PR approved / Peer reviewed 
- [ ] Security scans passed
- [ ] Automate accessibility tests passed
- [ ] Build process and deployment is automated and repeatable
- [ ] Feature toggles if appropriate
- [ ] Deploy to staging
- [ ] Move card to testing column in the board
---
**Staging**
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [ ] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [ ] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
**Some button styles, colors and labels may have changed and screenshots below may reflect outdated styles. Please refer to [Figma](https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=2750-62256&node-type=section&t=6lzkQqYVjlLF4EbT-0) for latest designs.**
Misalignment in styles, colors and labels should not affect the completion of development work. There will be additional user stories towards the end of this epic or MVP to bring uniformity to styles and colors.
If significant difference is noticed in features / functionality, please contact Renata.

![Image](https://github.com/user-attachments/assets/4363a29d-b591-40f5-bab7-b483125883af)
![Image](https://github.com/user-attachments/assets/812bebee-a91b-4725-a91f-80c0e15af573)
![Image](https://github.com/user-attachments/assets/e6a1636a-f6aa-4a15-aed4-d80fff76ae3b)
![Image](https://github.com/user-attachments/assets/737e98cb-38c4-48bd-8961-bf0d40992cc5)
![Image](https://github.com/user-attachments/assets/b676ec82-59a6-421e-9319-7cf510824e4f)

**Comment by r-bartlett-gsa** [comment]
@stepchud This is the user story that includes the "load more" option for the submissions list view. 

The average number of submissions for a challenge (on challenge.gov) is 46.3 submissions. The max number of submissions for a single challenge is 517. 

So loading in 20 submissions increment seems reasonable. Do you think there will be performance issues when a challenge has 500-1000 submissions?

**Comment by stepchud** [comment]
@r-bartlett-gsa everything on this specific list view can be QA'd _except_ Exports, which shouldn't impact anything else on here functionally.
wrt your question about performance, it's hard to predict performance without realistic testing, but I'd guess this can handle up to 1000 submissions on the table. I would treat high-volume performance as a future concern.
