### ISSUE TITLE
Evaluation forms list

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#60]
### User story
As a challenge manager, in order to manage all my evaluation forms efficiently, I would like to be able to review them in the list view and understand what the forms are for, and what actions I can take.

**Acceptance Criteria:**

- [x] The challenge manager can navigate to a list of evaluation forms via the dashboard or utility nav
- [x] If the user does not have any saved evaluations forms, the list is empty
  - [x] The user can start the process for creating a new evaluation form from this page
- [x] If the user has saved evaluations forms, the list of evaluation forms displays:
  - [x] Evaluation form name 
  - [x] Challenge name the form is assigned to (if any) (_note: challenge name is not a link to the challenge in Phoenix_)
  - [x] Evaluation period dates:
    - [x] Start date is the end date of the challenge the evaluation form is assigned to
    - [x] End date is set by the challenge manager during form creation
- [x] The user can choose the following options:
  - [x] Edit the form (the form cannot be edited (expect evaluation end date) if it's within or after evaluation period), #61 
  - [x] ~Delete the form (the form cannot be deleted if it's within or after evaluation period), #63~
  - [ ] Post-MVP: Clone, #62 
  - [ ] Post-MVP: Preview
- [x] From the list view, the user can select to create a new evaluation form, #61 

**Development tasks:**

- [x] #129
- [x] #130
- [x] #236 
- [ ] A11y review:
  - [ ] Screenreader is reading the 'Create New Evaluation Form' button twice in a row. Perhaps because the code should be role="button".
  - [ ] Table needs a name. 'No Accessibility markup found for this Element'.

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/0532a830-91a0-40ee-9a72-070a3b2eba86)

**Comment by stepchud** [comment]
I think there will be a lot of chicken/egg type problems like this, but I'm wondering purely from execution perspective how can we plan for delivering this in stages, i.e. without having the full functionality of the page and all the form cards implemented.

**Comment by stepchud** [comment]
How does the user navigate here? Can we add that to the ticket?

**Comment by r-bartlett-gsa** [comment]
> How does the user navigate here? Can we add that to the ticket?

@stepchud The user navigates to here from here: https://github.com/GSA/Challenge_platform/issues/53

**Comment by r-bartlett-gsa** [comment]
> I think there will be a lot of chicken/egg type problems like this, but I'm wondering purely from execution perspective how can we plan for delivering this in stages, i.e. without having the full functionality of the page and all the form cards implemented.

@stepchud Let's discuss this. I broken down the user stories so they can be delivered in stages, but if that does not address your concern I would like to learn more. Also, I realize that there will be parts/sections that we will need to come back to, after we implement something else, I think that's a normal part of the process.

**Comment by r-bartlett-gsa** [comment]
@stonefilipczak Do you have any recommendations on how to test this, given that the form creation work is not completed yet, and I cannot really create a form to have a list of forms. Should we wait until #61 and #65 are completed to test this? If so, that is is absolutely acceptable, but I was wondering if you know of an alternative way to test it.

**Comment by mhotch24** [comment]
Issues with getting into the system so usability and A11y testing can't be performed.

@stepchud is taking a look and will get back to me when resolved.

**Comment by mhotch24** [comment]
Stephen advised to delete browsers cache. Instead, I used an incognito window and that solved the caching issue. Will test that way going forward to avoid the multiple account issues.

@stepchud did suggest holding off on testing this card because there is not way for me to build my list of evaluations until the evaluation builder is ready.

**Comment by mhotch24** [comment]
I cannot test this page because the evaluation form builder is not complete. When I click save I get the following error: ![Image](https://github.com/user-attachments/assets/9413351d-d5af-4813-96ea-bc70d6ade29a)

**Comment by r-bartlett-gsa** [comment]
@stepchud Testing/review notes:

1. Evaluation period dates are not displayed
2. The delete button is implemented, even though it's not needed. Since only one form will be allowed for one challenge/phase and the form will be editable until challenge ends, we agreed that there's no need for delete button. _(The removal of the delete can be added to our future updates list)_

**Comment by stepchud** [comment]
@r-bartlett-gsa done! ✅

**Comment by r-bartlett-gsa** [comment]
@stepchud Looks great. Thank you!

**Comment by TCKapGrp** [comment]
@r-bartlett-gsa 
User Testing Feedback:

AC: If the user does not have any saved evaluations forms, the list is empty

>> I did not create any forms.  When I went to the Evaluation Forms Page I saw a form:
![Image](https://github.com/user-attachments/assets/e9b4b7f1-b1a9-42d9-b50d-f1240a9c9cd7)

Confirming that co-managers of a challenge should all see the form that is associated with the challenge?

**Comment by TCKapGrp** [comment]
@mhotch24, this can be a11y tested and responsive tested.

**Comment by mhotch24** [comment]
@r-bartlett-gsa I no longer have the ability to check off items. Can you check my permissions please? I am also unable to change the status back to Ally Fail per the process.

**Comment by mhotch24** [comment]
@stepchud  I found the following A11y issues:

1. Screenreader is reading the 'Create New Evaluation Form' button twice in a row. Perhaps because the code should be role="button" rather than nesting a button inside of an <a>.
2. Table needs a name. 'No Accessibility markup found for this Element'.

**Comment by r-bartlett-gsa** [comment]
@TCKapGrp Your account must be added as a co-manager on a challenge, and that's why you see the form. And yes being a co-challenge manager allows you to manage all the forms associated with that challenge. I verified that when the user has no forms, an appropriate page is displayed.

**Comment by stepchud** [comment]
This is ready to review again @r-bartlett-gsa @mhotch24 - the a11y issues should be resolved
