### ISSUE TITLE
Evaluation Form: Evaluation Criteria

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#67]
### User Story

As a challenge manager, in order to inform what evaluators should evaluate the submissions on, I would like to setup evaluation criteria.

**Acceptance criteria:**

- [x] A challenge manager can setup one scoring criteria at the time in Evaluation Form Creation workflow by providing the following criteria information:
  - [x] A checkbox to require evaluators to provide feedback/comments for each criteria
    - [ ] if checked will display a required open text area for the evaluator
  - [x] Radio buttons to indicate scale type, #69 (required field)
  - [x] An input field for Criteria title (required field)
  - [x] A text field for Criteria details / description (required field)
  - [x] A numerical input field for Criteria Points / weight (required field)
    - [x] The system validates if an input provided by a challenge manager is a whole number
    - [x] The input is used to calculate the criteria score and total score, https://github.com/GSA/Challenge_platform/issues/71
  - [x] Radio buttons for scoring type and conditional fields for rating scale options, #68 (required field)
- [x] A challenge manager can add additional criteria and go through criteria setup steps as outlined above for each one
- [x] Created criteria options can be edited and/or deleted before evaluation period starts

**Development tasks:**

- [ ] Task 1
- [ ] Task 2

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [ ] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [ ] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/70bde1a4-f2c9-4e7e-984d-475696215ff1)

**Comment by r-bartlett-gsa** [comment]
@stepchud / @cpreisinger 
10/21/24 Backlog Refinement Discussion:

- Criteria title field and criteria delete button will be pulled out from the accordion button as separate individual components:
  - Accordion title button label will say: Criteria 1, Criteria 2, etc
  - Criteria title field will be the first field within expanded accordion
  - Delete button will be at the bottom of expanded accordion, above Add Another Criteria button
- If there are any field validation errors within accordion, it will not allow to collapse and will show an error message indicating the error

**Comment by r-bartlett-gsa** [comment]
Moving testing feedback from #61 to this appropriate user story:

- When another criteria is added auto-collapse the previous criteria

**Comment by mhotch24** [comment]
@r-bartlett-gsa 

**Usability Feedback**
- Change page title to "Editing Evaluation Form"
- Form element titles should be bold.
- Should the criteria accordion default to open when it's only one or on the most recent one?
- Currently, you can add new criteria without completing the original. Should this be allowed?
- Criteria Points/Weight and Scoring Type should have same font type and style as Criteria Description, Criteria Title etc.
- Criteria Points/Weight text box should sit below title.
- Scoring Type should list horizontal like Scale Type radio buttons.

**Feature Specific A11y Feedback**
- Guidance (?) is missing some fields and isn't functioning.
- When keyboard is focused on any form elements and the user clicks Enter on keyboard, the form saves and takes the user to the confirmation page. For example: Keyboard tab to Step 2 / Require evaluators...check box. If user clicks Enter on the keyboard, the form saves and goes to confirmation page. 
- Move guidance outside of <label> or else is functions as the checkbox selector and not guidance.
- Add back breadcrumb above page title.

**Cross Browser Issues**
- **Windows/Chrome:** Asterix and (?) wrap to under Criteria Description title. ![Image](https://github.com/user-attachments/assets/b6e79303-9520-4478-ba64-1fe66690259f)

**Comment by r-bartlett-gsa** [comment]
Thank you @mhotch24 
Can you please provide some additional information for the following:

> When keyboard is focused on any form elements and the user clicks Enter on keyboard, the form saves and takes the user to the confirmation page. For example: Keyboard tab to Step 2 / Require evaluators...check box. If user clicks Enter on the keyboard, the form saves and goes to confirmation page.

What should happen instead when the user clicks enter?

> Move guidance outside of or else is functions as the checkbox selector and not guidance.

Should the tooltip icon be moved outside of checkbox selector?

Besides those items, most of your feedback will be moved to Fit & Finish work.

**Comment by mhotch24** [comment]
@r-bartlett-gsa 

1. It depends on what item they are focused on. But currently, most times when I press enter it will save. Happy to demonstrate.
2. Correct, the tooltip icon should be moved outside the checkbox selector.

**Comment by r-bartlett-gsa** [comment]
@stepchud Please address the following feedback:

- ✅ Move the tooltip icon outside of checkbox selector
- ✅ When another criteria is added auto-collapse the previous criteria
- ✅ Criteria Points/Weight input field should sit below title
- ✅ Remove criteria points field placeholder text, it's not necessary
- ✅ ~Removing a criteria requires a removal confirmation modal~

**Comment by mhotch24** [comment]
@r-bartlett-gsa updates on fails in the document for your review.

**Comment by stepchud** [comment]
> [@stepchud](https://github.com/stepchud) Please address the following feedback:
> 
> * ✅ Move the tooltip icon outside of checkbox selector
> * ✅ When another criteria is added auto-collapse the previous criteria
> * ✅ Criteria Points/Weight input field should sit below title
> * ✅ Remove criteria points field placeholder text, it's not necessary
> * ✅ ~Removing a criteria requires a removal confirmation modal~

@r-bartlett-gsa all of these tasks are now ready to test
