### ISSUE TITLE
Enter Evaluators

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#74]
### User story

As a challenge manager, in order to have the submissions of my challenge reviewed and scored by evaluators, I would like evaluators to be available within the system for assignment to submissions.

**Acceptance criteria:**

- [x] Within the submission management section for each challenge, a challenge manager can enter as many evaluators as needed for their challenge:
  - [x] An evaluator name (first and last name)
  - [x] An evaluator email address
  - [x] Once a new evaluator is added, they appear on the entered evaluator list 
- [x] Entered evaluators list shows the following information:
  - [x] First and last name
  - [x] Email address
  - [x] User role
    - [x] Evaluator
    - [x] Public Solver
    - [x] Challenge manager
  - [x] User status
    - [x] Invite sent (new users who are not in challenge.gov system and must create a new account)
    - [x] Available (an evaluator that is approved)
    - [x] Awaiting Approval (new users who created an account an are waiting for the admin to approve the account)
    - [ ] ~Role Change Needed (public solver or challenge manager in challenge.gov system who require their role changed to an evaluator by an admin user)~ #287 
  - [x] Number of assigned submissions for that challenge
  - [x] An option to delete an evaluator, #112 
  - [x] ~An option to view assigned submissions~ #179 
- [ ] ~Entered users are sent an email notification/invite notifying them of being assigned to challenge as an evaluator~ #97
- [x] Evaluator role approval process is the same as challenge managers role approval process
- [x] Entered users who are new to challenge.gov system are saved with an evaluator role 
  - [x] When an entered evaluator creates login.gov account for challenge.gov, they are able to login as an evaluator (and have appropriate permissions to site functions)
  - [x] If an entered evaluator already has an account with challenge.gov (challenge manager, public solver or admin roles), an appropriate role and status is displayed
    - [x] Entered user's role must be manually changed by an admin user
  - [ ] Post-MVP: If an entered evaluator already has an account with challenge.gov, they are assigned a second role of an evaluator and the next time they login, they have permissions of an evaluator role, https://github.com/GSA/Challenge_gov/issues/1361
- [ ] Entered and approved evaluators are available for assignment to submissions, #75 

**Dev tasks:**

- [x] #199
- [x] #200
- [x] #231
- [x] #245

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
**Some button styles, colors and labels may have changed and screenshots below may reflect outdated styles. Please refer to [Figma](https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=1239-32553&t=zejoVA9BLJ4A4DMM-1) for latest designs.**
Misalignment in styles, colors and labels should not affect the completion of development work. There will be additional user stories towards the end of this epic or MVP to bring uniformity to styles and colors.
If significant difference is noticed in features / functionality, please contact Renata.

![Image](https://github.com/user-attachments/assets/a3eec6e4-efd9-4868-ae99-5dd7f5828df9)

![Image](https://github.com/user-attachments/assets/4be6790a-75b0-4eb8-b3b0-6a880a1e3b6d)

![Image](https://github.com/user-attachments/assets/9896f468-aa66-4c1e-878b-da4c4a0a2dd4)

**Comment by r-bartlett-gsa** [comment]
@stepchud 

1. When a user who's already in challenge.gov system is entered as an evaluator we should save their name even the current record of that user does not have the name. Given that entering evaluators requires the name, we should save it.
 ![image](https://github.com/user-attachments/assets/258010c6-5691-41cb-8e3b-c781b1c3b293)
2. Form validation should show inline error messages
3. Is there a character limit for page title? This does not display a full challenge title, it should say "Eval Challenge - Test - Phase 1"
![image](https://github.com/user-attachments/assets/2c42335f-16e2-4496-8f55-e0f871127c06)
4. For Add to Evaluator List button, make icon decorative alt=”” so screen reader doesn’t repeat “Add evaluator” twice.
<img class="usa-icon--size-3 icon-white" alt="Add evaluator"
5. Please check DoD list

**Comment by r-bartlett-gsa** [comment]
Note: availability of evaluators for assignments will need to be tested at a later time once #75 is completed.
