### ISSUE TITLE
Submission Detail View for Challenge Managers

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#80]
### User story
As a challenge manager, in order to manage submissions and their evaluations process efficiently, I would like to be able to view all the details of a single submissions.

**Acceptance Criteria:**

- [x] From a submissions list view, a challenge manager can click on a submission and is displayed the following submission and evaluations information:
  - [x] Submission ID
  - [x] Submission and public solvers information (materials a public solver submitted as part of the entry):
    - [x] Brief description
    - [x] Description
    - [x] #284 
    - [x] External URL
    - [x] Submission status
    - [x] Submitter email
    - [x] Last updated date
- [x] A challenge manager has an option to either hide (collapse) submissions materials or open submission materials on a new tab
  - #304 
- [x] A challenge manager can select a submission for evaluation (formerly "pre-screen"), #81 
  - [x] If a submission is eligible for evaluation, a submission evaluation section is displayed, #85 
- [x] A challenge manager can select a submission for advancement, #84 
- [x] A challenge manager can enter and save notes for record keeping 
  - [x] Freeform input field is not required and is only saved and visible for challenge managers

**Development tasks:**

- [x] #284 
- [x] #345 
- [ ] ~#351~ 

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
- [x] Automated testing has been added or updated in response to changes in this PR
- [x] The feature is smoke tested to confirm it meets requirements
- [x] Database changes have been peer reviewed for index changes and performance bottlenecks
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
- [x] Automate accessibility tests passed
- [x] Build process and deployment is automated and repeatable
- [x] Feature toggles if appropriate
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Accessibility tested (Marni)
  - [x]  Keyboard navigation
  - [x]  Focus confirmed
  - [x] Color contrast compliance
  - [x] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
**Some button styles, colors and labels may have changed and screenshots below may reflect outdated styles. Please refer to [Figma](https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=2750-62256&node-type=section&t=6lzkQqYVjlLF4EbT-0) for latest designs.**
Misalignment in styles, colors and labels should not affect the completion of development work. There will be additional user stories towards the end of this epic or MVP to bring uniformity to styles and colors.
If significant difference is noticed in features / functionality, please contact Renata.

![Image](https://github.com/user-attachments/assets/204b8b9b-b26a-4176-a2f0-54d891a3b8ae)
---
![Image](https://github.com/user-attachments/assets/175421ab-e199-4929-bc19-548fe474c13f)
