### ISSUE TITLE
Submission Evaluation Details for Challenge Managers

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_platform#85]
### User story
As a challenge manager, in order to be able manage evaluation process for the submissions, I would like to be able to have control over who evaluates the submissions and have visibility into their evaluation progress.

**Acceptance criteria:** 
- [x] If a submission is marked as eligible for evaluation, a new Submission Evaluation section is displayed on the submission page and it allows a challenge manager:
  - [ ] ~View evaluation progress summary:~
    - [ ] ~Number of assigned evaluators~
    - [ ] ~Evaluations due date~
    - [ ] ~Number of completed evaluations~
    - [ ] ~Number of in progress evaluations~
    - [ ] ~Number of not started evaluations~
    - [ ] ~Average score, if all assigned evaluators completed their evaluations~
  - [x] See a list of assigned evaluators
    - [x]  Evaluator name
    - [x] Status #345
    - [x] Score (for completed evaluations) #345
    - [x] An option to view an evaluation, #180 
    - [x] An option to unassign an evaluator, #76 
    - [x] If no evaluators are assigned to a submission, a message is displayed indicating so
  - [x] See a list of available evaluators
    - [x] Evaluators name
    - [x] Evaluators email address
    - [x] An option to assign evaluators, #75 
    - [x] An option to manage evaluators
    - [x] If no evaluators are available, a message is displayed indicating so
- [x] If a challenge of this submission does not have an evaluation form created/assigned, a message is displayed indicating so, and Submission Evaluation section is not displayed

**Dev tasks:**

- [x] #304
- [x] #305
- [x] Submission Assignment: See Issue #75

### Definition of Done

**Doing (dev team)**
- [ ] Code complete 
- [ ] Code is organized appropriately
- [ ] Any known trade offs are documented in the associated GH issue
- [ ] Code is documented, modules, shared functions, etc.
- [ ] Automated testing has been added or updated in response to changes in this PR
- [ ] The feature is smoke tested to confirm it meets requirements
- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks
- [ ] PR that changes or adds UI
  - [ ] include a screenshot of the WAVE report for the altered pages
  - [ ] Confirm changes were validated for mobile responsiveness
- [ ] PR approved / Peer reviewed 
- [ ] Security scans passed
- [ ] Automate accessibility tests passed
- [ ] Build process and deployment is automated and repeatable
- [ ] Feature toggles if appropriate
- [ ] Deploy to staging
- [ ] Move card to testing column in the board
---
**Staging**
- [ ] ~Accessibility tested (Marni)~
  - [ ]  ~Keyboard navigation~
  - [ ] ~Focus confirmed~
  - [ ] ~Color contrast compliance~
  - [ ] ~Screen reader testing~
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [x] Windows/Chrome
  - [x] Windows/Edge
  - [x] Mac/Chrome
  - [x] Mac/Safari
  - [x] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata / Tracy / Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
![Image](https://github.com/user-attachments/assets/2bbf77e6-36a0-4a9c-8526-8de294657b75)

**Comment by r-bartlett-gsa** [comment]
**Some button styles, colors and labels may have changed and screenshots below may reflect outdated styles. Please refer to [Figma](https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=2750-62256&t=6lzkQqYVjlLF4EbT-1) for latest designs.**
Misalignment in styles, colors and labels should not affect the completion of development work. There will be additional user stories towards the end of this epic or MVP to bring uniformity to styles and colors.
If significant difference is noticed in features / functionality, please contact Renata.

![Image](https://github.com/user-attachments/assets/c07b6970-24a0-4006-88be-b49febc2eb7e)
![Image](https://github.com/user-attachments/assets/0cf42398-9900-4162-9c81-0a80c509c979)
![Image](https://github.com/user-attachments/assets/9c2ceed4-055c-489f-a72e-852d18ef2a6a)
![Image](https://github.com/user-attachments/assets/9980bcc6-7155-45de-9375-a612f54070dd)
![Image](https://github.com/user-attachments/assets/48cc331c-d731-4a09-94d6-52b7c9a5e55f)

**Comment by r-bartlett-gsa** [comment]
@stonefilipczak and @stepchud Given that the evaluation summary dashboard (stats dashboard) is problematic on this split submission detail page, let's eliminate it for the MVP.

**Comment by stepchud** [comment]
@r-bartlett-gsa this can be tested now, the button linking to CM view of completed evaluations is implemented but the view itself is not.
